Spring:
    profiles:
    active:
    - dev
---
Spring:
    profiles: dev 
    application:
        name: micorservicecloud-config-dev
---
Spring:
    profiles: test 
    application:
        name: micorservicecloud-config-test